# .github/workflows/ci-cd.yml
name: publish to pypi

on:
  push:
    branch:
      - main

  jobs:
    pypi-publish:
      name: Upload release to PyPI
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/maswavespytest
      permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
        
      - name: Build and generate wheel file
        run: python -m build --wheel

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          build_dir: ./dist
