# .github/workflows/ci-cd.yml
name: publish to pypi

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      run: python -m pip install cibuildwheel==2.16.2
      with:
        python-version: '3.11'

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

    - name: Build and generate wheel file
      run: |
        python -m pip install --user --upgrade build
        python -m cibuildwheel --output-dir dist

  deploy:
    name: Publish package distributions to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Public wheels to PyPI test
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
