# .github/workflows/ci-cd.yml
name: publish to pypi

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build-and-publish-to-pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Build and generate wheel file
      run: |
        python -m pip install --user --upgrade build
        python -m build --wheel

    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
