# .github/workflows/ci-cd.yml
name: publish to pypi

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Test with pytest
      run: |
        python -m pytest tests/


  build_wheels:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [run_tests]
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.2

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
    
  build_sdist:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [run_tests]
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi

    steps:
    - name: Download packages
      uses: actions/download-artifact@v3
      with:
        # unpacks default artifact into dist/
        # if `name: artifact` is omitted, the action will create extra parent dir
        name: artifact
        path: dist
  
    - name: Publish wheels to PyPI test
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
